
modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
[[mods]] #mandatory
# The modid of the mod
modId="${mod_id}" #mandatory
# The version number of the mod
version="${mod_version}" #mandatory
# A display name for the mod
displayName="${mod_name}" #mandatory
description='''${mod_description}'''
[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]] #optional
modId="neoforge" #mandatory
type="required" #mandatory
versionRange="[${neo_version},)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.survivorsdelight]]
modId="farmersdelight"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.survivorsdelight]]
modId="survivorsabilities"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"